name: ci

on: push

jobs:
  build:
    runs-on: macos-latest
    if: github.repository == 'cheonjaewoong/compose-grid'
    strategy:
      matrix:
        api: [21, 23, 29]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: '11'

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api }}
          script: ./gradlew connectedDebugAndroidTest --stacktrace
