name: ci

on: push

jobs:
  build:
    runs-on: macos-latest
    if: github.repository == 'cheonjaewoong/compose-grid'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup jdk
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: '17'

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest --stacktrace
